{
 "title": "queryTest",
 "time": { "from": "2026-01-16T03:22:32.463Z", "to": "2026-01-16T04:39:15.742Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "tomcat_threads_busy_threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tomcat_threads_busy_threads", "legendFormat": "busy_threads" }
   ]
  },
  {
   "title": "tomcat_threads_current_threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tomcat_threads_current_threads", "legendFormat": "current_threads" }
   ]
  },
  {
   "title": "hikaricp_pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_pending", "legendFormat": "{{job}}-pending" }
   ]
  },
  {
   "title": "hikmaricp_active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "{{job}}-actvie" }
   ]
  },
  {
   "title": "DB 트랜잭션/초",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"app\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hikaricp_timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total",
     "legendFormat": "{{job}}-timeout"
    }
   ]
  }
 ]
}